### ISSUE TITLE
What's the plan for group chat, audio and video call？

### ISSUE THREAD

**Issue by godpit** [tigase/stork#27]
What's the plan for group chat, audio and video call？

**Comment by licaon-kter** [comment]
Maybe split this into 3 issues: groups, audio calls and video calls?

**Comment by woj-tek** [comment]
@godpit They are all implemented. If you lack some specific function please create new issue and describe in detail what's expected.

**Comment by licaon-kter** [comment]
I only see Video call, with Conversations as contact, are audio-only calls possible too?

**Comment by woj-tek** [comment]
Currently only `Video chat` is possible.
