### ISSUE TITLE
How to create a chat room for stork,I can just join room

### ISSUE THREAD

**Issue by ChenMoGe2** [tigase/stork#35]
It is maybe a question not bug.I can just join chat room but I can't create it.When I join a new chat room,it always says 'Invalid room address,please check and try again'.

My tigase server version is 8.1.2,and my config.tdsl file for muc is
```
muc () {
}
```

It is some wrong for my properties or the stork doesn't support for create chat room.
If it can join chat room,what address should I input
Thank you!

**Comment by woj-tek** [comment]
Which address did you provide to join/create the room? It shouldn't make a difference.

I just tried and it worked without an issue.

**Comment by ChenMoGe2** [comment]
@woj-tek Thank you
Hello,I did not found where I can create the room,so I have no room address.I can just create the room address written in database directly or other place?

**Comment by ChenMoGe2** [comment]
Update
I joined a chat room already,but the devices in the chat room can not chat with each others.Is my properties in config.tdsl is wrong?

**Comment by woj-tek** [comment]
> Hello,I did not found where I can create the room,so I have no room address.I can just create the room address written in database directly or other place?

It's done in the same place - "Join chatroom". If the room exists you will simply join. If not - it will be created.

> I joined a chat room already,but the devices in the chat room can not chat with each others.Is my properties in config.tdsl is wrong?

Your configuration is ok.

Did you create the room in Stork? I tested it yesterday and it worked just fine.

**Comment by ChenMoGe2** [comment]
@woj-tek  Thank you,maybe something configuration was wrong,I paste my complete configuration here

`admins = [
    xxx
]
'config-type' = 'default'
debug = [ 'server' ]
'default-virtual-host' = 'xx.xx.xxx'
dataSource () {
    default () {
        uri = 'jdbc:mysql://xxx:xxx/tigasedb?user=im&password=123456&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true'
    }
}
http () {
    setup () {
        'admin-password' = 'xxxxxxx'
        'admin-user' = 'xxx'
    }
}
pubsub () {
    trusted = [ 'http@{clusterNode}' ]
}
message-archive () {
}
muc() {
    defaultRoomConfig {
    	'tigase#presence_delivery_logic' = 'PREFERE_LAST'
    	'muc#roomconfig_persistentroom' = 'true'
    }
}


'sess-man' {
    amp () {}
    message (active: true) {}
    msgoffline (active: true) {}
    'http://jabber.org/protocol/jingle' (class: tigase.xmpp.impl.Jingle,active: true) {
    	threadsNo = 1
    }
    'presence-offline' (class: tigase.xmpp.impl.PresenceOffline,
        active: false) {
        threadsNo = 1
    }
    'presence-state' (class: tigase.xmpp.impl.PresenceState) {
        threadsNo = 1
    }
    'presence-subscription' (class: tigase.xmpp.impl.PresenceSubscription) {
        threadsNo = 1
    }
    'jabber:iq:roster' {
        'auto-authorize' = 'true'
    }
    'presence-subscription' () {
        'auto-authorize' = 'true'
    }
}
`

All of my configuration is here,I use my private service.I can't chat with each others and the tables(tig_muc_rooms,tig_muc_room_history and tig_muc_room_affiliations) in mysql are empty after I create room or send messages in the chat room.

**Comment by ChenMoGe2** [comment]
@woj-tek Thank you,maybe something configuration was wrong,I paste my complete configuration here

`admins = [
xxx
]
'config-type' = 'default'
debug = [ 'server' ]
'default-virtual-host' = 'xx.xx.xxx'
dataSource () {
default () {
uri = 'jdbc:mysql://xxx:xxx/tigasedb?user=im&password=123456&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true'
}
}
http () {
setup () {
'admin-password' = 'xxxxxxx'
'admin-user' = 'xxx'
}
}
pubsub () {
trusted = [ 'http@{clusterNode}' ]
}
message-archive () {
}
muc() {
defaultRoomConfig {
'tigase#presence_delivery_logic' = 'PREFERE_LAST'
'muc#roomconfig_persistentroom' = 'true'
}
}

'sess-man' {
amp () {}
message (active: true) {}
msgoffline (active: true) {}
'http://jabber.org/protocol/jingle' (class: tigase.xmpp.impl.Jingle,active: true) {
threadsNo = 1
}
'presence-offline' (class: tigase.xmpp.impl.PresenceOffline,
active: false) {
threadsNo = 1
}
'presence-state' (class: tigase.xmpp.impl.PresenceState) {
threadsNo = 1
}
'presence-subscription' (class: tigase.xmpp.impl.PresenceSubscription) {
threadsNo = 1
}
'jabber:iq:roster' {
'auto-authorize' = 'true'
}
'presence-subscription' () {
'auto-authorize' = 'true'
}
}
`

All of my configuration is here,I use my private service.I can't chat with each others who join the chat room and the tables(tig_muc_rooms,tig_muc_room_history and tig_muc_room_affiliations) in mysql are empty after I create room or send messages in the chat room.

**Comment by ChenMoGe2** [comment]
I have tested at public service named tigase.im,and it can't chat each others in chat room.

**Comment by ChenMoGe2** [comment]
The question can't chat each others in chat room is resolved,the chat room address must start with muc. .Like muc.tigase.im not tigase.im

**Comment by licaon-kter** [comment]
It depends on how you setup the group/conference component, right?

**Comment by ChenMoGe2** [comment]
> It depends on how you setup the group/conference component, right?

Yeah,the question is resolved.It's my fault.I should create chat room address end with muc.xxx.xxx

**Comment by woj-tek** [comment]
@licaon-kter while it's true it's kinda unorthodox/unpopular? And could cause some headaches?

**Comment by licaon-kter** [comment]
@woj-tek you mean the lack of a component subdomain for groups? The personalised name or?

**Comment by woj-tek** [comment]
The former - the subdomain.

**Comment by licaon-kter** [comment]
Yes, an afaik unfortunately it's not a standardised thing. You're not forced to have that.
