### ISSUE TITLE
Can not goto VideoChatActivity from chat room

### ISSUE THREAD

**Issue by ChenMoGe2** [tigase/stork#37]
**Describe the bug**
can not goto VideoChatActivity from chat room

**To Reproduce**
1. Go to 'a group chat'
2. Click on 'Video Chat'
3. Have no response

**Expected behavior**
can video chat with others who is in the chat room

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: Android 9,10

**Additional context**
I checked the stork code at org.tigase.messenger.phone.pro.conversations.muc.MucActivity and I didn't found any code about muc video chat.Does the stork support the video chat in chat room?

**Comment by licaon-kter** [comment]
Multi user video conference is not yet that well defined, no. Maybe host Jitsi Meet (still XMPP fyi) alongside.

**Comment by ChenMoGe2** [comment]
@licaon-kter Thank you
