### ISSUE TITLE
What i can do to create an account with  a ip domain(the server is local server which is run in eclipse)

### ISSUE THREAD

**Issue by wqxcloud** [tigase/stork#38]
What i can do to create an account with a ip domain(the server is local server which is run in eclipse) 
thanks very much
![image](https://user-images.githubusercontent.com/23133414/118668470-7b7da800-b827-11eb-9755-56142fc1d344.png)

**Comment by woj-tek** [comment]
You MUST not use IP as the domain name. Please configure the VHost on your installation to match the hostname of your machine that would be resolvable within the network.

Unfortunately Stork doesn't allow you to specify hostname during account creation.

However, once you have the account in the system you can add it to stork and there specify the hostname.

**Comment by wqxcloud** [comment]
> You MUST not use IP as the domain name. Please configure the VHost on your installation to match the hostname of your machine that would be resolvable within the network.
> 
> Unfortunately Stork doesn't allow you to specify hostname during account creation.
> 
> However, once you have the account in the system you can add it to stork and there specify the hostname.

ok thanks very much
