### ISSUE TITLE
Using a newer webrtc lib

### ISSUE THREAD

**Issue by licaon-kter** [tigase/stork#41]
For the F-Droid build Conversations and some of its fork switched to using the newer builds eg. `'ch.threema:webrtc-android:100.0.0'` provided by Threema for their own Android app.

The issue is that their build is patched for their needs: https://github.com/threema-ch/webrtc-build-docker/tree/master/patches

And some Conversations forks (Cheogram, Snikket and Conversations from Play Store) can't use that since the patches break calls with https://jmp.chat users.

Is Stork affected by those patches? Can the Threema build be used?

The current lib provided by Google in maven, that Stork uses, is already >2years old and many CVEs have been fixed, eg. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11496#note_1047414675

**Comment by licaon-kter** [comment]
Or https://search.maven.org/artifact/im.conversations.webrtc/webrtc-android/104.0.0/aar like Conversations/Quicksy?

**Comment by licaon-kter** [comment]
https://www.openwall.com/lists/oss-security/2023/09/28/5

**Comment by arthef** [comment]
Thank you for heads up but we no longer develop or maintain stork app. We are working on a new app which is planed to be soon released and code published.

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/6293917baa8ead01743363c2113f7c408c361560
