### ISSUE TITLE
PlayStore / F-Droid problem

### ISSUE THREAD

**Issue by Neustradamus** [tigase/stork#47]
Stork IM is missing here:
- https://play.google.com/store/apps/details?id=org.tigase.messenger.phone.pro
- https://f-droid.org/packages/org.tigase.messenger.phone.pro/

**Comment by licaon-kter** [comment]
/close this

https://github.com/tigase/stork/issues/41#issuecomment-2143037673

Read https://f-droid.org/2024/06/06/twif.html

**Comment by Neustradamus** [comment]
@licaon-kter: Thanks for the article!

Maybe good to have an application before the multi-platform app?

**Comment by arthef** [comment]
Unfortunately, Stork maintenance was too expensive and it stopped working on more recent Android versions. It was upsetting users who tried to use it. Therefore, we decided to remove it from the Google Play Store and focus our effort son the new app.
The development is already very advanced and the app is quite usable, so we will release it soon. We might first release it to Google Play Store first in the current state. We do not want to publish source code until the app is finished.
